### ISSUE TITLE
Inconvenient demo usage for sizing

### ISSUE THREAD

**Issue by zhangpzh** [rockeyben/DCCF#11]
I was just playing around with your official github repo. And I found that in the interactive demo. The 'original-size' option in the script/predict_interactive.py is not implemented. But I think merely resizing operation as described in the args docstrings is still insufficient. Since according to the paper, the learned filters (1x1 convs) should be able to directly apply to the original image right ?  So I start resorting to the evaluation demo but find it is restricted to evaluation only on predefined harmony dataset. For user-customized dataset, it seems to inconvenient. Looking forward to your help.

Empirically for the interactive demo usage, no matter for the officially provided images (little girls) or my customized image. the resulting image resolution seems both reduced 5x times smaller.

**Comment by rockeyben** [comment]
Sorry for delayed reply.
It seems that the output of our network is 'original-size' by default. 
[This line of code](https://github.com/rockeyben/DCCF/blob/master/scripts/predict_interactive.py#L291C17-L291C56) caused your '5x times smaller problem', due to memory issue. You can comment out this line and don't concatenate these param settings to get direct output.
